name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install Xvfb and other dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb openjdk-11-jdk

    - name: Run Xvfb
      run: |
        Xvfb :99 -screen 0 1024x768x24 &
        export DISPLAY=:99
        sleep 5  # Give Xvfb a moment to start

    - name: Build with Maven
      run: mvn install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: target/*.jar

    - name: Run Unit Tests
      run: xvfb-run mvn test

    - name: Upload Test Reports
      uses: actions/upload-artifact@v3
      with:
        name: test-reports
        path: target/surefire-reports/

    - name: Generate Code Coverage Report
      run: mvn jacoco:report

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: target/site/jacoco/
