name: CI 
 
on: 
  push: 
    branches: [ master ] 
  pull_request: 
    branches: [ master ] 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout code 
      uses: actions/checkout@v3 
 
    - name: Set up JDK 11 
      uses: actions/setup-java@v3 
      with:  
        java-version: '11' 
 
    - name: Build with Gradle 
      run: gradle build  
 
    - name: Upload Build Artifacts 
      uses: actions/upload-artifact@v3 
      with: 
        name: build-artifacts 
        path: build/libs/** 
 
    - name: Run Unit Test 
      run: gradle test 
 
    - name: Upload Test Reports 
      uses: actions/upload-artifact@v3 
      with: 
        name: test-reports 
        path: build/reports/tests/** 
    - name: Generate code coverage report 
      run: gradle jacocoTestReport 
 
    - name: Upload code coverage report 
      uses: actions/upload-artifact@v3 
      with: 
        name: code-coverage-report 
        path: build/reports/jacoco/test/html/** 
         
    - name: Run Deployment 
      run: java -jar build/libs/calculator-app-1.0-SNAPSHOT.jar